name: tests

on: [push, pull_request]

jobs:

  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      # max-parallel: 4
      matrix:
        os: [ubuntu]  # Add macos and windows
        python-version: [3.7, 3.8, 3.9]
        numpy-version: [1.19.*, 1.20.*, 1.21.*]
        compat-test-arg: ["numpy.lib.tests.test_io::TestLoadTxt",
                          "numpy.lib.tests.test_regression::TestRegression::test_loadtxt_fields_subarrays"]
        compat-test-ignore: ["test_converters_decode,test_converters_nodecode,test_comments_multiple,test_str_dtype,test_dtype_with_object,test_from_float_hex,test_universal_newline,test_binary_load"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest hypothesis
        python -m pip install numpy==${{ matrix.numpy-version }}

    - name: Install npreadtext
      run: |
        python -m pip install -e . --verbose

    - name: Test with pytest
      run: |
        pytest

    - name: loadtxt-compat-regression
      run: |
        python compat/check_loadtxt_compat.py -v 3 -t ${{ matrix.compat-test-arg }} --ignore ${{ matrix.compat-test-ignore }}

    - name: Run C tests
      run: |
        cd src/ctests
        bash build_runtest.sh
        ./runtests

  loadtxt-full-compat:
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: true
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu]  # Add macos and windows
        python-version: [3.9]
        numpy-version: [1.21.*]
        test-arg: ["numpy.lib.tests.test_io::TestLoadTxt",
                   "numpy.lib.tests.test_regression::TestRegression::test_loadtxt_fields_subarrays"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest hypothesis
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install npreadtxt
      run: |
        python -m pip install -e . --verbose
    - name: Test with pytest
      run: |
        python compat/check_loadtxt_compat.py -v 3 -t ${{ matrix.test-arg }}
